site_name: bblocks
site_url: https://ONECampaign.github.io/bblocks
repo_url: https://github.com/ONECampaign/bblocks
repo_name: ONECampaign/bblocks
#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: api.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - bblocks
