name: Draft Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  release:
    name: Create Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-versions: [ "3.10" ]

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry git-changelog
          poetry install

      - name: Build the package
        run: poetry run poetry build

      - name: Generate changelog
        run: poetry run git-changelog > CHANGELOG.md

      - name: Create Draft GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*.whl
          draft: true  # Set to true to make it a draft release
          prerelease: false
          body_path: CHANGELOG.md  # Automatically include changelog