# this workflow will upload the package to pypi when a new release is created
name: release

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    name: Release package to PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry

      - name: Install package
        run: poetry install

      - name: Build wheels and source tarball
        run: poetry build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true
          verify_metadata: true
          verbose: true