# this workflow runs unit tests and checks code style
# for different versions of python on different operating systems

name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.py }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, py: "3.13" }
          - { os: ubuntu-latest, py: "3.12" }
          - { os: windows-latest, py: "3.11" }
          - { os: macOS-latest, py: "3.11" }
          - { os: ubuntu-latest, py: "3.11" }

    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.config.py }}

      - name: Install package
        run: uv sync

      - name: Test with pytest
        run: uv run pytest tests/ --cov=./ --cov-report=xml

      - name: Code coverage
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: true # optional (default = false)
          name: codecov-umbrella # optional
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true # optional (default = false)

      - name: Check code style
        run: uv run black src tests --check
